spring:
  application:
    name: EUREKA-SERVICE

server:
  port: ${EUREKA_SERVICE_PORT}
  max-http-request-header-size: 256KB

eureka:
  instance:
    hostname: EUREKA-SERVICE
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://EUREKA-SERVICE:8761/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: '*'  # For debugging, can be narrowed to just 'health' later
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework: INFO